version: "3"

services:
  nuxt-docker-example:
    container_name: nuxt-docker-example
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./database/neo4j/logs:/logs
      - ./database/neo4j/config:/config
      - ./database/neo4j/data:/data
      - ./database/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/letmeinletmein
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt, mapped to host port 7685
    restart: always

  neo4j-seeder:
    build: ./seeder # Dockerfile that sets up your seed script
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687 # <-- Use 'neo4j' as hostname, port 7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=letmeinletmein
    command: ["python", "seed.py"]
