version: "3"

services:
  nuxt-docker-example:
    container_name: nuxt-docker
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${NUXT_FRONTEND_PORT_MAPPING}"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./database/neo4j/logs:/logs
      - ./database/neo4j/config:/config
      - ./database/neo4j/data:/data
      - ./database/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_DATABASE_PORT_MAPPING_1}" # HTTP Browser
      - "${NEO4J_DATABASE_PORT_MAPPING_2}" # Bolt, mapped to host port 7685
    restart: always

  backend:
    container_name: fastapi-application
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${FAST_API_BACKEND_PORT_MAPPING}"
    depends_on:
      - neo4j

  neo4j-seeder:
    container_name: neo4j-seeder
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:${NEO4J_DATABASE_PORT_2} # <-- Use 'neo4j' as hostname, port 7687
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASS=${NEO4J_PASSWORD}
      - NEO4J_DATABASE_PORT_2=${NEO4J_DATABASE_PORT_2}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SEED=${SEED}
      - MODEL_TYPE=${MODEL_TYPE}
